//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7alazon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Booking
    {
        [Key]
        public int BookingID { get; set; }
        [ForeignKey("UserID")]

        public int UserID { get; set; }
        [ForeignKey("RoomID")]

        public int RoomID { get; set; }
        [DataType(DataType.Date)]
        [Required]
        public System.DateTime CheckIn { get; set; }
        [DataType(DataType.Date)]
        [Required]
        public System.DateTime CheckOut { get; set; }
        [Required]
        public string Etat { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
