//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7alazon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Comment
    {
        [Key]
        public int CommentID { get; set; }
        [ForeignKey("RoomID")]
        public int UserID { get; set; }
        [ForeignKey("RoomID")]
        public int HotelID { get; set; }
        [Required]
        public string Comment1 { get; set; }
        [DataType(DataType.Date)]
        [Required]
        public System.DateTime CommentDate { get; set; }

        public virtual Hotel Hotel { get; set; }
        public virtual User User { get; set; }
    }
}
