//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7alazon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.Comments = new HashSet<Comment>();
            this.Rooms = new HashSet<Room>();
        }

        public int HotelID { get; set; }
        [Required]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.")]
        public string HotelName { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.")]

        public string HotelAddress { get; set; }
        [Required]
        [Phone(ErrorMessage = "Invalid Phone Number")]

        public string HotelPhoneNumber { get; set; }
        [Required]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]

        public string HotelEmail { get; set; }
        [Required]
        public int HotelRating { get; set; }
        [Required]
        public string Photo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
